# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
imports:
    - { resource: "@UserBundle/Resources/config/security.yml" }

security:

    role_hierarchy:
            ROLE_STUDENT:     ROLE_USER
            ROLE_PROF:        ROLE_USER
            ROLE_ADMIN:       ROLE_USER
            ROLE_SUPER_ADMIN:
                - ROLE_ADMIN
                - ROLE_USER
                - ROLE_PROF
                - ROLE_STUDENT
                - ROLE_ALLOWED_TO_SWITCH

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
